[project]
name = "eigenface"
version = "0.1.0"
description = "Aineopintojen harjoitustyö"
authors = [
    {name = "Roope",email = "roope.kaikkonen@helsinki.fi"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow (>=12.2.0,<13.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pylint (>=4.0.5,<5.0.0)",
    "autopep8 (>=2.3.2,<3.0.0)",
    "pytest (>=9.0.3,<10.0.0)"
]
